baseURL = "https://dustinnewman.me"
languageCode = "en-us"
title = "Dustin Newman"
theme = "paper"

[[menu.main]]
name = "Posts"
url = "/posts"

[[menu.main]]
name = "Projects"
url = "/projects"

[[menu.main]]
name = "Recipes"
url = "/recipes"

[markup.highlight]
style = "monokai"
