baseURL = "https://dustinnewman.me"
languageCode = "en-us"
title = "Dustin Newman"
theme = "clean"

[[menu.main]]
name = "home"
url = "/"

[[menu.main]]
name = "posts"
url = "/posts"

[[menu.main]]
name = "projects"
url = "/projects"

[markup.highlight]
style = "monokai"
